### ISSUE TITLE
Outdated Documentation?

### ISSUE THREAD

**Issue by kkloberdanz** [NLeSC/ShiCo#30]
In the README it says to run the server with:

python shico/server.py -f "word2vecModels/195?_????.w2v"

I'm not seeing the file shico/server.py. Is the documentation outdated?

Thank you

**Comment by c-martinez** [comment]
Hi @kkloberdanz,

Yes, sorry, documentation is out of date due to an improvement made last week to be able to run with [gunicorn](http://gunicorn.org/).

You can run the flask app directly by running:

```
$ python shico/server/app.py -f "word2vecModels/195?_????.w2v"
```

Alternatively, if you want to use gunicorn, you can update your server configuration in `shico/server/config.py` (instead of from the command line) and then run:

```
gunicorn --bind 0.0.0.0:5000 shico.server.wsgi:app
```

I'll update the documentation as soon as possible, but in the mean time, I hope this is enough to get you started (do ask if it doesn't work for you).

**Comment by kkloberdanz** [comment]
Thank you!

**Comment by c-martinez** [comment]
Documentation is now up to date.
